### ISSUE TITLE
Update to the latest version of FluentAssertions?

### ISSUE THREAD

**Issue by thomOrbelius** [BrianSchroer/sparky-test-helpers#21]
Hi, the SparkyTestHelpers.Moq.Fluent helpers seems really nice. 
My question is if you are planning to bump the target version of FluentAssertions? The current target version for SparkyTestHelpers.Moq.Fluent is 5.5.3 and the latest public available version is 6.2.0.

BR /Thom

**Comment by BrianSchroer** [comment]
I finally got around to doing this today and published version 1.5 to NuGet. Thank you for your patience.

**Comment by thomOrbelius** [comment]
Nice @BrianSchroer . Are there any plans on creating a new nuget package for this? (Don't know if you are planning to include anything else)

**Comment by BrianSchroer** [comment]
@thomOrbelius Yes, I created the NuGet package on 12/29 - https://www.nuget.org/packages/SparkyTestHelpers.Moq.Fluent/

**Comment by thomOrbelius** [comment]
Sorry, missed that. I have now added the correct nuget and also made a pull request #22 with som additional helpers.
