### ISSUE TITLE
Populater.CreateRandom<T>() creates duplicate instances

### ISSUE THREAD

**Issue by Samurai303** [BrianSchroer/sparky-test-helpers#5]
When calling Populater.CreateRandom<T>() for two of the same object, the properties values are the same.
Take a simple class
```
public class DataTest
{
	public string DataLine1 { get; set; }
	public string DataLine2 { get; set; }
	public bool UseData { get; set; }
}
```
Then the following code returns the same values for both instances
```
var data1 = populater.CreateRandom<DataTest>();
var data2 = populater.CreateRandom<DataTest>();
```
It seems to be down to the RandomValueProvider creating it's own instance of Random() with the same seed.

**Comment by BrianSchroer** [comment]
Thanks for reporting it. It's fixed with version 1.3.2.
