### ISSUE TITLE
Target .NET Framework

### ISSUE THREAD

**Issue by james1301** [BrianSchroer/sparky-test-helpers#6]
Could you Target .NET Framework in all of your different nugets please? There are a lot of .net standard dependencies getting installed in all of our projects.

We specifically use:
SparkyTestHelpers (.net 4.6.1 or .net standard 1.3) Already done
SparkyTestHelpers.Moq (.net standard 1.3)
SparkyTestHelpers.Moq.Core (.net standard 1.3)
SparkyTestHelpers.Populater (.net standard 1.5)

**Comment by BrianSchroer** [comment]
Thanks for letting me know about the issue.

I've made the updates and published to NuGet.

Please let me know (or make a pull request) if it looks like it's been done incorrectly.

**Comment by james1301** [comment]
Looks good, thanks @BrianSchroer.
